version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://corvus:corvus@postgres:5432/corvus
      - NEO4J_URI=neo4j://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=corvuspass
    depends_on:
      - postgres
      - neo4j

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=corvus
      - POSTGRES_PASSWORD=corvus
      - POSTGRES_DB=corvus
    volumes:
      - postgres_data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/corvuspass
    volumes:
      - neo4j_data:/data

volumes:
  postgres_data:
  neo4j_data:
